---
title: "Mean Step 2 ES calculation for general pattern"
author: "Keisuke Atsumi"
date: '`r format(Sys.time(), "%y/%m/%d %H:%M")`'
output:
  html_document:
    code_folding: hide
    theme: united
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}

rm(list=ls())  # reset workspace
options(scipen=100)  # do not show numbers using exponential

# install & load packages
# install.packages("tidyverse" ,"metafor", "openxlsx", "data.table")
pacman::p_load(
  tidyverse,
  magrittr,
  metafor,
  knitr,
  rotl,
  kableExtra,
  pander,     # nice tables
  ape,        # Phylogeny
  phytools,   # Phylogeny
  svglite,    # Export SVG plots
  ggiraphExtra # Geom predict

)
opts_chunk$set(prompt=TRUE, message=FALSE, comment="", warning = FALSE) 

# check multicolinearity (calculate VIF)
# https://github.com/pedroj/RCode_Master_UPO/blob/master/Statistical%20protocol_Zuur%20etal/sm001/HighstatLib.r

mytheme <- 
  theme(
    panel.grid = element_blank(),
    axis.title = element_text(size=12),
    axis.text = element_text(size=11),
    axis.text.x = element_text(angle = 30, hjust = 1),
    strip.text = element_text(size=12, lineheight=5.0),
    strip.background = element_rect(fill = "lightgrey")
  )


```

# Calculating effect sizes for meta-analysis
Phenotypic difference from spSS to the other crosses

```{r lnRR & SMD between hybrids and parental species}

# load phenotypic data
dat <- read.csv("../data/dat.mean.csv", head = TRUE)

# Order by taxon
dat$taxa <- ordered(
  dat$taxa,
  levels = c("Neuroptera", "Coleoptera", "Diptera", "Lepidoptera", "Orthoptera", "Aves", "Rodentia", "Anura", "Cichliformes")
  )

### Difference between hybrids and smaller species (spS) ###

for (i in c("hybLS", "hybSL", "spL")) { # identify type of hybrids
  for (h in c("spS")) { # identify type of parentals
    assign(
      paste(i, h, sep = "_"),
      
      left_join(
        ### lnRR ###
        escalc(
          measure = "ROM",
          # N of hybrids
          n1i = dat[, paste("N", i, sep = ".")],
          # N of parentals
          n2i = dat[, paste("N", h, sep = ".")],
          # Mean of hybrids
          m1i = dat[, paste("Mn", i, sep = ".")],
          # Mean of parentals
          m2i = dat[, paste("Mn", h, sep = ".")],
          # SD of hybrids
          sd1i = dat[, paste("SD", i, sep = ".")],
          # SD of parentals
          sd2i = dat[, paste("SD", h, sep = ".")],
          data = dat
          ) %>%
          rename(lnRR.es = yi, lnRR.sv = vi),
        ### SMD ###
        escalc(
          measure = "SMD",
          # N of hybrids
          n1i = dat[, paste("N", i, sep = ".")],
          # N of parentals
          n2i = dat[, paste("N", h, sep = ".")],
          # Mean of hybrids
          m1i = dat[, paste("Mn", i, sep = ".")],
          # Mean of parentals
          m2i = dat[, paste("Mn", h, sep = ".")],
          # SD of hybrids]
          sd1i = dat[, paste("SD", i, sep = ".")],
          # SD of parentals
          sd2i = dat[, paste("SD", h, sep = ".")],
          data = dat
          ) %>%
          rename(SMD.es = yi, SMD.sv = vi)
        ) %>%
        
        select(ES.ID, contains("lnRR"), contains("SMD")) %>%
        # indicate type of hybrid
        mutate(cross = i) 
    )
  }
}

mean.dif <- bind_rows(
  hybLS_spS, hybSL_spS, spL_spS
  ) %>%
  drop_na(SMD.sv) %>%
  arrange(ES.ID) %>%
  left_join(., dat) 

write.csv(
  mean.dif %>%
    filter(reciprocal == "Viable"), 
  "../data/mean.ES.general.csv", row.names = F
  )

write.csv(
  mean.dif, "../data/mean.ES.general.alldat.csv", row.names = F
  )

```

# Phenotypic data sumamry

```{r dataset summary, results='asis'}

summary <- mean.dif %>%
  group_by(taxa) %>%
  summarise(
    species.pair = length(unique(species.pair)),
    observations = length(unique(ES.ID)),
    study = length(unique(Study.ID))
    )

bind_rows(
  summary,
  summary %>%
    summarise_if(is.numeric, sum) %>%
    mutate(taxa = "total")
  ) %>%
  column_to_rownames(var = "taxa") %>%
  kable("html", digits = 3) %>% kable_styling("striped", position = "left")

# Order by taxon

sum.forplot <- summary %>% 
  gather(key = metrics, value = N, -taxa)
sum.forplot$metrics <- ordered(
  sum.forplot$metrics,
  levels = c(
    "study", "species.pair", "observations"
    )
  )

plot <- ggplot(sum.forplot, aes(x = "", y = N, fill = taxa)) +
  geom_bar(width = 1, stat = "identity") +
  scale_fill_brewer() +
  facet_grid(scale = "free", rows = "metrics") +
  xlab("") +
  mytheme
plot

# ggsave(plot = plot, file = "../Analysis/phenodat.additive.svg", height = 5, width = 3.5)

```


# Funnel plots

```{r funnel plot}

res <- rma(
  yi = lnRR.es, vi = lnRR.sv, 
  data = mean.dif, method="FE"
  )

### set up 2x2 array for plotting
par(mfrow=c(2,2))
 
### draw funnel plots
funnel(res, main="Standard Error", xlim = c(-2, 4))
funnel(res, yaxis="vi", main="Sampling Variance", xlim = c(-2, 4))
funnel(res, yaxis="seinv", main="Inverse Standard Error", xlim = c(-2, 4))
funnel(res, yaxis="vinv", main="Inverse Sampling Variance", xlim = c(-2, 4))

```
# Check data
Checked data of extremely high/low standard error and confirmed that those data were correctly imported. 

```{r check, results='asis'}

outliers <- mean.dif %>%
  # vi (sampling variance) 
  mutate(SE = sqrt(lnRR.sv)) %>%
  arrange(desc(SE)) %>%
  filter(SE > 1.2 | 1/SE > 140) %>%
  select(ES.ID, File, SE, cross, reciprocal, trait, Cross.ID) %>%
  mutate_if(is.numeric, round, 3)

outliers %>%
  kable("html", digits = 3) %>% kable_styling("striped", position = "left")

write.csv(
  mean.dif, "../data/mean.ES.general.csv", row.names = F
  )

```


# Phylogeny

```{r phylogeny}

# matching names from open tree taxonomy
taxa <- tnrs_match_names(
  names = levels(mean.dif$spL.name) %>%
    str_replace_all("_", " "), 
  context_name = "Animals"
  )

# which names return more than 1 match?
inspect(taxa, ott_id = taxa$ott_id[taxa$number_matches != 1])

# fixing names with more than 1 match
taxa[taxa$number_matches != 1, ] <- 
  inspect(taxa, ott_id = taxa$ott_id[taxa$number_matches != 1])[1, ]

tree <- tol_induced_subtree(ott_ids = taxa$ott_id)
tree$tip.label %<>%
  strip_ott_ids(remove_underscores=TRUE)

print("Original tree from OTL")
plot(tree, no.margin=TRUE)

# randomly solve non-binary phylogeny
set.seed(6)
bin.tree <- multi2di(tree, random = T) 
print("Randomly solved phylogeny")
plot(bin.tree)

# correlation matrix to fit to the model
bin.tree$tip.label <- bin.tree$tip.label %>%
  as.factor() 

levels(bin.tree$tip.label) <- levels(mean.dif$spL.name) # making sure names match
bin.tree$tip.label <- as.character(bin.tree$tip.label) # converting names back to character

write.tree(bin.tree, file= "../data/phylo.mean.general.tre")

```
  