---
title: "Title"
author: "Keisuke Atsumi, Losia Lagisz & Shinichi Nakagawa"
date: '`r format(Sys.time(), "%y/%m/%d %H:%M")`'
output:
  html_document:
    code_download: true
    code_folding: hide
    theme: united # “default”, “cerulean”, “journal”, “flatly”, “darkly”, “readable”, “spacelab”, “united”, “cosmo”, “lumen”, “paper”, “sandstone”, “simplex”, “yeti”
    toc: yes
    toc_float: yes
subtitle: Electronic Supplementary Material

---
## Setup

### Load packages

```{r}

rm(list=ls())  # reset workspace
options(scipen=100)  # do not show numbers using exponential

# install & load packages
pacman::p_load(
  openxlsx   # open excel
  , tidyverse
  , magrittr   # extended pipe
  , MCMCglmm   # comparative analysis
  , rotl       # open tree of life
  , ape        # Phylogeny
  , phytools   # Phylogeny
  , knitr  
  , kableExtra # nice tables
  , pander     # nice tables
  , ggtree
  # , R.rsp
)

# Rmarkdown settings
knitr::opts_chunk$set(
  prompt  = FALSE,  # Do not add > or + in inline-code
  message = FALSE, 
  comment = "", 
  warning = FALSE,  # Mute warnings
  tidy    = TRUE
  ) 
options(knitr.kable.NA = '') # Hide NAs in kable table

## Phenotype data ##
pheno <- read.xlsx(
    "../data/original.data.xlsx", sheet = "Phenotype"
    ) %>%
  # Excluding data without any parent data
  drop_na(contains("SD.sp")) %>%
  # to numeric
  mutate_at(
    vars(contains("Mn") | contains("SD") | N.sp1:N.sp2), 
    as.numeric
    ) %>%
  # delete observation with negative mean trait value
  filter(Mn.sp1 > 0 & Mn.sp2 > 0 & homologous == "Yes") %>%   
  # calculate phenotypic difference between parental species
  mutate(
    Pheno.divergence = abs(log(Mn.sp1/Mn.sp2))
    ) %>%
  mutate_at(vars(contains("pheno.div")), scale) %>%
  # describe whether full cross or not
  mutate(
    Reciprocal = ifelse(
      is.na(Mn.hyb12 & Mn.hyb21), 
      "Inviable", "Viable"
      )
    )

meta <- read.xlsx(
    "../data/original.data.xlsx", sheet = "Metadata"
    ) %>%
  mutate_at(vars(contains("divergence")), as.numeric) %>%
  # Logalize genetic divergence
  mutate_at(vars(contains("divergence")), log10)

```




```{r}

dat <- original.dat %>%
  select(Study.ID, Cross.ID, taxa, Genus, contains("Mn")) %>%
  # Gather reciprocal hybrid data
  gather(
    key = Hybrid, value = Mn.hybrid, 
    -c(Study.ID, Cross.ID, taxa, Genus), -contains("Mn.sp")
    ) %>%
  drop_na(Mn.hybrid) %>%
  # Calculate standardized hybrid phenotype mean
  mutate(
    Dominance = ifelse(
      Mn.sp1 > Mn.sp2, 
      (Mn.hybrid - Mn.sp2)/abs(Mn.sp1 - Mn.sp2),
      (Mn.hybrid - Mn.sp1)/abs(Mn.sp1 - Mn.sp2)
    )
  ) %>%
  mutate_at("Cross.ID", as.factor) %>%
  arrange(taxa, Genus, Cross.ID, Hybrid) %>%
  # only get crosses with > 2 traits
  # Reciprocal hybrids are separated
  group_by(Cross.ID, Hybrid, taxa, Genus, Study.ID) %>%
  filter(n() > 2) %>%
  # Create all combinations of standardized hybrid phenotype mean
  do(data.frame(t(combn(.$Dominance, 2)))) %>%
  # Calculate dominance mismatch
  mutate(
    Mismatch = sqrt(2) * sqrt( X1^2 + X2^2 - ( (X1 + X2) / sqrt(2) )^2 ),
    Mismatch.log = log(Mismatch)
  ) %>%
  left_join(meta) %>%
  mutate_if(is.character, as.factor) %>%
  within(taxa <- ordered(taxa, levels = c("Neuroptera", "Coleoptera", "Diptera", "Lepidoptera", "Orthoptera", "Aves", "Rodentia", "Anura", "Cichliformes"))) %>%
  as.data.frame

dat %>% 
  summarise(
    'Trait combination' = length(X1),
    'Species pair' = length(unique(species.pair)),
    'Crossing' = length(unique(Cross.ID))
    ) %>% 
  kable("html") %>% kable_styling("striped", position = "left")

ggplot(data = dat, aes(x = Cross.ID, y = Mismatch)) +
  geom_point(alpha = 0.4, aes(color = Hybrid)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~taxa, scales = "free")

ggplot(
  data = dat %>%
    filter(!grepl("musculus", Cross.ID)), 
  aes(x = Cross.ID, y = Mismatch)) +
  geom_point(alpha = 0.4, aes(color = Hybrid)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~taxa, scales = "free")

ggplot(data = dat, aes(x = Cross.ID, y = Mismatch.log)) +
  geom_point(alpha = 0.4, aes(color = Hybrid)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~taxa, scales = "free")

#++++++++++++++++++++++++++++++++++#
# Phylogenetic tree for mcmcglmm 
#++++++++++++++++++++++++++++++++++#

# compute branch lengths of tree
phylo_branch <- read.tree(file = "../data/phylo.novelty.tre") %>%
  compute.brlen(method = "Grafen", power = 1)
plot.phylo(phylo_branch, cex = 0.7)

# # saving phylogeneic matrix
# phylo_cor <- vcv(phylo_branch, cor = T)
# 
# # generating inverse phylogenetic matrix for MCMCglmm
# phylo_branch$node.label <- NULL
# phylo_MCMC <- MCMCglmm::inverseA(phylo_branch, nodes = "ALL", scale = TRUE)$Ainv

dat2 <- drop_na(dat, Mismatch.log)

#++++++++++++++++++++++++++++++++++++++++++++++++++++#
# MCMCglmm for phylogenetic comparative analysis
#++++++++++++++++++++++++++++++++++++++++++++++++++++#

# ### Log mismatch data ###
# phylmix <-MCMCglmm(
#   fixed = Mismatch.log ~  1,
#   # idh(SE):units | weight by SE of effect size
#   random = ~ Study.ID + sp1.name + Cross.ID + Hybrid,
#   verbose = FALSE,
#   ginverse = list(sp1.name = phylo_MCMC),
#   data = dat2
# )
# saveRDS(phylmix, file = "../Analysis/mismatch.log.obj")

# ### Log mismatch data ###
# phylmix <-MCMCglmm(
#   fixed = Mismatch ~  1,
#   # idh(SE):units | weight by SE of effect size
#   random = ~ Study.ID + sp1.name + Cross.ID + Hybrid,
#   verbose = FALSE,
#   ginverse = list(sp1.name = phylo_MCMC),
#   data = dat
# )
# saveRDS(phylmix, file = "../Analysis/mismatch.obj")

### Load model ###
phylmix <- readRDS("../Analysis/mismatch.obj")

### Fixed effects output ###
print("Mean mismatch domminance considering heterogeneity through study, phylogeny, crossed strain and cross direction")
summary(phylmix)$solutions

### Random effects output ###  
summary(phylmix$VCV)$statistics %>%
  as.data.frame %>%
  kable("html", digits = 3, caption = "Random effects") %>% 
  kable_styling("striped", position = "left")

```
