---
title: "Transgression in mean & variation"
author: "Keisuke Atsumi"
date: '`r format(Sys.time(), "%y/%m/%d %H:%M")`'
output:
  html_document:
    code_folding: hide
    theme: united
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE, message = FALSE}

rm(list=ls())  # reset workspace
sessionInfo()  # show R version etc
options(scipen=100)  # do not show numbers using exponential

# install & load packages
pacman::p_load(
  openxlsx,   # open excel
  tidyverse,  
  kableExtra,
  pander,     # nice tables
  MCMCglmm,   # glmm
  knitr,      # rmarkdown
  magrittr,   # Extend pipe
  rotl,       # Create phylogeny from Open Tree of Life
  ape,        # Phylogeny
  phytools,   # Phylogeny
  svglite,    # Export SVG plots
  ggiraphExtra, # Geom predict
  patchwork   # combine multiple plots
)
opts_chunk$set(prompt=TRUE, message=FALSE, comment="", warning = FALSE) 
options(knitr.kable.NA = '') # Hide NAs in kable table

```

```{r}

dat <- read.csv("../data/dat.transgression.csv", head = TRUE) %>% 
  mutate_at(vars("mean.TS.occur", "var.TS"), as.factor) %>% 
  within(
    var.TS <-
      ordered(var.TS, levels = c(-1, 0, 1)),
    mean.TS.occur <- 
      ordered(mean.TS.occur, levels = c(0, 1))
  )

#++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# Read create tree based on Open Tree of Life taxonomy
#++++++++++++++++++++++++++++++++++++++++++++++++++++++#

# # matching names from open tree taxonomy
# taxa <- tnrs_match_names(
#   names = levels(dat$sp1.name) %>%
#     str_replace_all("_", " "),
#   context_name = "Animals"
#   )
# 
# # Create tree
# tree <- tol_induced_subtree(ott_ids = taxa$ott_id)
# tree$tip.label %<>%
#   strip_ott_ids # remove OTT IDs from tip labels
# # randomly solve non-binary phylogeny
# set.seed(6)
# bin.tree <- multi2di(tree, random = T)
# print("Randomly solved phylogeny")
# 
# # Indicate mismatch between tip labels & dataset species names
# setdiff(levels(as.factor(bin.tree$tip.label)), levels(dat$sp1.name))
# setdiff(levels(dat$sp1.name), levels(as.factor(bin.tree$tip.label)))
# # Fix names of tip labels
# bin.tree$tip.label %<>% str_replace_all("Dryophytes", "Hyla")
# 
# write.tree(bin.tree, file= "../data/phylo.TS.tre")

#++++++++++++++++++++++++++++++++++#
# Phylogenetic tree for mcmcglmm 
#++++++++++++++++++++++++++++++++++#

# compute branch lengths of tree
phylo_branch <- read.tree(file = "../data/phylo.TS.tre") %>%
  compute.brlen(method = "Grafen", power = 1)
plot(phylo_branch)

# saving phylogeneic matrix
phylo_cor <- vcv(phylo_branch, cor = T)

# generating inverse phylogenetic matrix for MCMCglmm
phylo_branch$node.label <- NULL
phylo_MCMC <- MCMCglmm::inverseA(phylo_branch, nodes = "ALL", scale = TRUE)$Ainv

```

```{r}

dat %>% 
  group_by(mean.TS.occur, var.TS) %>% 
  summarise('N (Trait observation)' = length(ES.ID)) %>% 
  spread(key = mean.TS.occur, value = 'N (Trait observation)') %>%
  as.data.frame() %>%
  rename(
    'Existent' = '0',
    'Novel' = '1',
    'Variability' = 'var.TS'
    ) %>%
  within(levels(Variability) <- c("Smaller", "-", "Greater")) %>%
  mutate(
    "Existent phenotype (% trait obs)" = 
      Existent/sum(Existent)*100, 
    "Novel phenotype (% trait obs)" = 
      Novel/sum(Novel)*100
  ) %>%
  kable("html") %>% kable_styling("striped", position = "left")

```


# Phylogenetic ordinal (probit) regression
```{r}

# prior1<-list(
#   B=list(
#     mu=c(0,0), 
#     V=gelman.prior(~mean.TS.occur, data=select(dat, -trait), scale=sqrt(1+1))
#     ),
#   R=list(V=1,fix=1),
#   G = list(
#     G1 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
#     G2 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
#     G3 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
#     G4 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000)
#     )
#   )
# 
# phylmix <-MCMCglmm(
#   fixed = var.TS ~ mean.TS.occur,
#   family = "ordinal",
#   random = ~ Study.ID + Cross.ID + sp1.name + ES.ID,
#   verbose = FALSE,
#   prior = prior1,
#   ginverse = list(sp1.name = phylo_MCMC),
#   data = select(dat, -trait),
#   nitt = 60000,  # Increase the number of iterations, default is 13000
#   burnin = 5000  # Increase the number of burnin, default is 3000
#   )
# 
# ### Save model ###
# saveRDS(phylmix, file = "../Analysis/transgression.mean.var.obj")

### Load model ###
phylmix <- readRDS("../Analysis/transgression.mean.var.obj")

summary(phylmix)


```