---
title: "Greater or smaller phenotypic variance in hybrids"
author: "Keisuke Atsumi"
date: '`r format(Sys.time(), "%y/%m/%d %H:%M")`'
output:
  html_document:
    code_folding: hide
    theme: united
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}

rm(list=ls())  # reset workspace
sessionInfo()  # show R version etc
options(scipen=100)  # do not show numbers using exponential

# install & load packages
pacman::p_load(
  openxlsx,   # open excel
  tidyverse,  
  MCMCglmm,   # glmm
  MuMIn,      # model selection
  knitr,      # rmarkdown
  magrittr,   # Extend pipe
  ape,        # Phylogeny
  phytools,   # Phylogeny
  svglite,    # Export SVG plots
  devtools    # Install from Github
)

# Install patchwork
devtools::install_github("thomasp85/patchwork")

opts_chunk$set(prompt=TRUE, message=FALSE, comment="", warning = FALSE) 

```

# transgressive segregation


```{r transgressive segregation}

dat <- read.csv("../data/variation.ES.TS.csv", head = TRUE) %>%
  # Assign transgressive segregation to 1, no TS to 0 for each effect size
  mutate(TS = ifelse(yi < 0, 1, 0)) %>%
  ### Join with metadata ###
  left_join(
    .,
    read.xlsx(
      "../data/original.data.xlsx", sheet = "Metadata"
      )
    ) %>%
  mutate_at(vars(divergence.cytb:surv.relat.hyb21), as.numeric) %>%
  mutate_at(
    vars(contains("divergence"), contains("surv.relat")), scale
    ) %>%
  as.data.frame %>%
  select(-trait) %>%
  drop_na(hetero.sex, pheno.div.diff, trait.type, divergence.COI) %>%
  # order taxon
  within(
    taxa <- ordered(
      taxa,
      levels = c(
        "Teleost", "Amphibian", "Bird", "Mammal",
        "Diptera", "Lepidoptera", "Neuroptera", 
        "Orthoptera","Coleoptera" 
        )
      )
    ) %>%
  mutate_if(is.character, as.factor)

#### Phylogenetic tree for mcmcglmm ####

# compute branch lengths of tree
phylo_branch <- read.tree(file = "../data/phylo.variation.TS.tre") %>%
  compute.brlen(bin.tree, method = "Grafen", power = 1)

# saving phylogeneic matrix
phylo_cor <- vcv(phylo_branch, cor = T)

# generating inverse phylogenetic matrix for MCMCglmm
# Note one of the tips is called "Lates calcarifer (estimated)"
phylo_branch$node.label <- NULL
phylo_MCMC <- MCMCglmm::inverseA(phylo_branch, nodes = "ALL", scale = TRUE)$Ainv

```

# Frequency of TS
How frequent the TS is?  

```{r freq of od}

print("overall frequency of TS")
dat %>%
  group_by(TS) %>%
  summarise(length(unique(ES.ID)))

summary <- bind_rows(
  # All observations
  dat %>%
    group_by(taxa) %>%
    summarise(
      species.pair = length(unique(species.pair)),
      observations = length(unique(ES.ID)),
      study = length(unique(Study.ID))
      ) %>%
    mutate(direction = "All Observations")
  ,
  # TS observations
  dat %>%
    filter(TS == "1") %>%
    group_by(taxa) %>%
    summarise(
      species.pair = length(unique(species.pair)),
      observations = length(unique(ES.ID)),
      study = length(unique(Study.ID))
      ) %>%
    mutate(direction = "Any directions")
  ,
  dat %>%
    filter(TS == "1") %>%
    group_by(taxa, direction) %>%
    summarise(
      species.pair = length(unique(species.pair)),
      observations = length(unique(ES.ID)),
      study = length(unique(Study.ID))
      )
  ) %>%
  # Assign 0 for no observation of TS
  replace(., is.na(.), "0") %>%
  # Make tidy data
  gather(key = metrics, value = N, -c(taxa, direction)) %>%
  # Order factors
  mutate_at(vars("metrics", "direction"), as.factor) %>%
  # Order taxon
  within(
    metrics <- ordered(
      metrics,
      levels = c("study", "species.pair", "observations")
      )
  ) %>%
  # Order TS category
  within(
    direction <- ordered(
      direction,
      levels = c("All Observations", "Any directions", "+", "-")
      )
    ) %>%
  # Change names of TS category to more intuitive name
  within(
    levels(direction) <- c("All Observations", "All deviations", "Greater variation", "Smaller variation")
      ) %>%
  filter(metrics != "study")
  
### Plot ###
plot <- ggplot(summary, aes(x = "", y = N, fill = taxa)) +
  geom_bar(width = 1, stat = "identity") +
  scale_fill_brewer() +
  facet_grid(
    scale = "free", metrics ~ direction,
    # strip text into two lines
    labeller = label_wrap_gen(width = 13)
    ) +
  xlab("") +
  theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )
plot

ggsave(plot = plot, file = "../Analysis/Variation.TS.frequency.svg", height = 4, width = 6)

### Total number of observations and percentage ###
summary %>%
  group_by(direction, metrics) %>%
  # Count number of observaitons and species pairs
  summarise(sum(N)) %>%
  spread(key = metrics, value = "sum(N)") %>%
  as.data.frame() %>%
  # Calculate percentage
  mutate(
    percent.species.pair = species.pair/.[1, "species.pair"]*100,
    percent.observations = observations/.[1, "observations"]*100
  ) %>%
  mutate_at(vars(contains("percent")), round, 2)


```


# Seeking factor influences the frequency of transgressive segregation

```{r mixed model}

### Setting prior to logistic regression ###
prior <- list(
  B=list(
    mu = rep(0, 17), # N of coefficient. (level -1) for categorical factors, 1 for continuous factors, 1 for intercept  
    V = gelman.prior(~ 
    parental*hetero.sex + parental*direction +
    direction*divergence.COI + direction*pheno.div.ratio + 
    direction*hetero.sex + direction*trait.type +
    direction*distribution + direction*reciprocal,
    data = dat, # formula and data
    scale=sqrt(pi^2/3+1))), # error distribution of logistic regression
  R=list(V=1,fix=1),
  # Replicating same G for the number of random effects (here, 4)
  G = list(
    G1 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
    G2 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
    G3 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
    G4 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000)
    )
  )

### Model selection for MCMCglmm ###
MCMCglmm.updateable<- updateable(MCMCglmm)

### Phylogenetic binomial regression ###
phylmix <-MCMCglmm.updateable(
  fixed = TS ~  
    parental*hetero.sex + parental*direction +
    direction*divergence.COI + direction*pheno.div.ratio + 
    direction*hetero.sex + direction*trait.type +
    direction*distribution + direction*reciprocal,
  family = "categorical",
  # idh(SE):units | weight by SE of effect size
  random = ~ Study.ID + Cross.ID + spL.name + idh(SE):units,
  verbose = FALSE,
  ginverse = list(spL.name = phylo_MCMC), 
  prior = prior,
  data = dat
)


### Correcting estimate ###
c2 <- (16 * sqrt(3)/(15 * pi))^2

sum <- left_join(
  # corrected estimates & SD
  summary(phylmix$Sol/sqrt(1+c2))$statistics %>%
    as.data.frame() %>%
    rownames_to_column(var = "factors"),
  # P
  summary(phylmix)$solutions %>%
  as.data.frame() %>%
  rownames_to_column(var = "factors"),
  by = "factors"
  ) %>%
  mutate(significance = ifelse(pMCMC < 0.05, "*", "")) %>%
  ### Grouping factors ###
  mutate(
    group = ifelse(str_detect(factors, "direction.:"), 
                   "increasing trait value",
                   ifelse(str_detect(factors, "parentalMother:"),
                          "polar overdominance",
                          ifelse(factors == "hetero.sexmale:direction+",
                                 "increasing trait value",
                                 "transgressive segregation"
                                 )
                          )
                   )
  ) %>%
  mutate_at("group", as.factor) %>%
  within(group <- ordered(group, c("transgressive segregation", "increasing trait value", "polar overdominance"))) %>%
  ### Change factor names ###
  within(
    factors <- str_remove_all(
      factors, "direction.:"
      ) %>%
      str_remove_all(., "parentalMother:") %>%
      str_remove_all(., ":direction.")
    ) %>%
  within(
    factors <- factor(
      factors, ordered = TRUE, 
      levels = c("trait.typesound", "hetero.sexmale", "parentalMother", "reciprocalViable", "distributionOverlap", "pheno.div.ratio", "sq.divergence.COI", "divergence.COI",  "direction+", "(Intercept)")
      )
    )

### Plot ###
metaplot <- ggplot(sum, aes(
  x = post.mean, 
  # Inverse order of factors
  y = factors
  )) +
  # Vertical line
  geom_vline(
    xintercept = 0, size = 0.3, 
    colour = "grey30", linetype = "dotted"         
    ) +
  # CI
  geom_errorbarh(
    aes(
      xmin = sum[, 'l-95% CI'], xmax = sum[, 'u-95% CI'],
      colour=significance 
      ), 
    height = .0001
    ) +
  # Color of plots and errorbars
  scale_colour_manual(values = c("grey60", "black")) +
  geom_point(size = 1.5, aes(colour = significance)) +
  scale_fill_manual(values = c("grey60", "black")) +
  # Title
  ylab("") + xlab("estimate with CI") +
  # Combine different plots for main factors and interactions
  facet_grid(group~., scales = "free", space = "free") +
  # Themes
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    legend.position = "none",
    panel.border=element_blank(),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 12),
    axis.line=element_line(colour = "grey70")
    )
print(metaplot)

ggsave(
    plot = metaplot, 
    file = "../Analysis/variation.TS.result.svg", 
    height = 6.75, width = 4.6
    )

### Output result ###

print(
  sum %>% 
    select(group, factors, Mean, SD, pMCMC, significance) %>%
    mutate_at(c("Mean", "SD"), round, 2)
  )

# transformation for varaince
summary(phylmix$VCV/(1+c2))

```
*direction+* greater variation in hybrids  


# Direct test for the significant categorical factors

```{r Direct test for the significant categorical factors}


#####################################################
# Direct test for the significant categorical factors
#####################################################

### Correcting estimate ###
c2 <- (16 * sqrt(3)/(15 * pi))^2

for (i in c("reciprocal", "trait.type")) {

  # Make new categorical data combining direction of TS and target categorical factor
  dat %<>%
    mutate(interaction = str_c(direction, .[, i], sep = "_"))

  ### Setting prior to logistic regression ###
  prior <- list(
    B=list(
      mu = rep(0, 4), # N of coefficient. (level -1) for categorical factors, 1 for continuous factors, 1 for intercept
      V = gelman.prior(~ interaction, # + trait.direction
      data = dat, # formula and data
      scale=sqrt(pi^2/3+1))), # error distribution of logistic regression
    R=list(V=1,fix=1),
    # Replicating same G for the number of random effects (here, 4)
    G = list(
      G1 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
      G2 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
      G3 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000),
      G4 = list(V = 1, nu = 1, alpha.mu = 0, alpha.V = 1000)
      )
    )
  
  phylmix <-MCMCglmm(
    fixed = TS ~  interaction -1, # + trait.direction
    family = "categorical",
    # idh(SE):units | weight by SE of effect size
    random = ~ Study.ID + Cross.ID + spL.name + idh(SE):units,
    verbose = FALSE,
    ginverse = list(spL.name = phylo_MCMC),
    prior = prior,
    data = dat
  )

  assign(
    paste("sum", i, sep = "."),
    left_join(
      # corrected estimates & SD
      summary(phylmix$Sol/sqrt(1+c2))$statistics %>%
        as.data.frame() %>%
        rownames_to_column(var = "factors"),
      # P
      summary(phylmix)$solutions %>%
      as.data.frame() %>%
      rownames_to_column(var = "factors"),
      by = "factors"
      ) %>%
      mutate(group = i) %>%
      within(factors <- str_remove_all(factors, "interaction")) %>%
      mutate(
        significance = ifelse(pMCMC < 0.05, "*", ""),
        direction = 
          ifelse(str_detect(factors, "\\+"), 
                 "increase variation", "decrease variation")
        ) 
  )

}

sum.categorical <- bind_rows(sum.reciprocal, sum.trait.type) %>%
  as.data.frame() %>%
  within(factors <- str_remove_all(factors, "interaction")) %>%
  mutate(
    significance = ifelse(pMCMC < 0.05, "*", ""),
    direction = ifelse(str_detect(factors, "\\+"), "Increase variation", "Reduce variation")
    ) 

### Plot ###
categoricalplot <- ggplot(
  sum.categorical, aes(x = post.mean, y = factors)
  ) +
  # Vertical line
  geom_vline(
    xintercept = 0, size = 0.3, 
    colour = "grey30", linetype = "dotted"         
    ) +
  # CI
  geom_errorbarh(
    aes(
      xmin = sum.categorical[, 'l-95% CI'], 
      xmax = sum.categorical[, 'u-95% CI'],
      ), 
    height = .0001
    ) +
  geom_point(size = 2.0, shape = 17) +
  # Title
  ylab("") + xlab("estimate with CI") +
  # Combine different plots for main factors and interactions
  # Themes
  theme_bw() +
  # Combine different plots for main factors and interactions
  facet_grid(
    group + direction ~., scales = "free", drop = TRUE,
    labeller = label_wrap_gen(width = 13)
    ) +
  theme(
    panel.grid = element_blank(),
    legend.position = "none",
    panel.border = element_blank(),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 12),
    axis.line=element_line(colour = "grey70")
    )
print(categoricalplot)

ggsave(
    plot = categoricalplot, 
    file = "../Analysis/variation.TS.categorical.svg", 
    height = 4, width = 5
    )

```


